name: multi_media_picker
description: A fork of the official image_picker plugin that adds the functionality to pick multiple images.
version: 0.1.2
author: Javi Hurtado <webmaster@javi-h.com>
homepage: https://github.com/ja2375/multi_media_picker

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^0.7.2

flutter:
  plugin:
    androidPackage: com.javih.multimediapicker
    pluginClass: MultiMediaPickerPlugin
